import config from "../../../config";
const URL = config.REACT_APP_URL;

export const sections = [
    {
        title: "About CSS Gradients",
        content: `The CSS Gradient online generator tool is a nice and simple to use utility to quickly generate linear and radial color gradients. You can create the gradients and export the CSS code with colors in HEX or RGB format.
        <br><br>
        Keep reading below to learn more about <a href="${URL}/#css-linear-gradients" id="ref">Linear Gradients</a>, <a href="${URL}/#css-radial-gradients" id="ref">Radial Gradients</a> or <a href="${URL}/#css-text-gradients" id="ref">Text Gradients</a>.
        <br><br>
        <span itemscope="" itemtype="http://www.schema.org/SiteNavigationElement">
        Or, get inspired and discover more gradient backgrounds by color: <span itemprop="name"><a itemprop="url" href="${URL}/red-gradient-backgrounds" id="ref">Red gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/orange-gradient-backgrounds" id="ref">Orange gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/yellow-gradient-backgrounds" id="ref">Yellow gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/green-gradient-backgrounds" id="ref">Green gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/azure-gradient-backgrounds" id="ref">Azure gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/blue-gradient-backgrounds" id="ref">Blue gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/purple-gradient-backgrounds" id="ref">Purple gradient backgrounds</a></span>, <span itemprop="name"><a itemprop="url" href="${URL}/pink-gradient-backgrounds" id="ref">Pink gradient backgrounds</a></span> or <span itemprop="name"><a itemprop="url" href="${URL}/monochrome-gradient-backgrounds" id="ref">Monochrome gradient backgrounds</a></span>.
        </span>`
    },
    {
        title: "CSS Gradients Browser compatibility",
        content: `<table class="table">
        <thead>
          <tr class="title">
            <th>IE</th>
            <th>Edge</th>
            <th>Firefox</th>
            <th>Chrome</th>
            <th>Safari</th>
            <th>Opera</th>
            <th>iOS Safari</th>
            <th>Opera
                <br>Mini</th>
            <th>Android
                <br>Browser</th>
            <th>Chrome
                <br>Android</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>10+</td>
            <td>12+</td>
            <td>16+</td>
            <td>26+</td>
            <td>6.1+</td>
            <td>12</td>
            <td>7.1+</td>
            <td>x</td>
            <td>4.4+</td>
            <td>46+</td>
          </tr>
        </tbody>
      </table>`
    },
    {
        title: "What is a CSS Gradient?",
        content: `<p class="quote">
        CSS3 gradients let you display smooth transitions between two or more specified colors.<br>
        Earlier, you had to use images for these effects. However, by using CSS3 gradients you can reduce download time and bandwidth usage. In addition, elements with gradients look better when zoomed, because the gradient is generated by the browser.<br>
        <br>
        CSS3 defines two types of gradients:<br>
        - <a href="${URL}/#css-linear-gradients" id="ref">Linear Gradients</a> (direction down/up/left/right/diagonally)<br>
        - <a href="${URL}/#css-radial-gradients" id="ref">Radial Gradients</a> (defined by their center)<br>
        <br>
        Definition from <a href="https://www.w3schools.com/csS/css3_gradients.asp" rel="nofollow" target="_blank" id="ref">W3Schools</a>
      </p>
      <br><br>
      <p class="quote">
        The &lt;gradient&gt; CSS data type denotes a CSS &lt;image&gt; made of a progressive transition between two or more colors. A CSS gradient is not a CSS &lt;color&gt; but an image with no intrinsic dimensions; that is, it has no natural or preferred size, nor a preferred ratio. Its concrete size will match the one of the element it applies to.
        <br><br>
        There are three kinds of color gradients:<br>
        - linear gradients, generated by the linear-gradient() function, where the color smoothly fades along an imaginary line.<br>
        - radial gradients, generated by the radial-gradient() function. The more away from an origin a point is, the more far from the original color it is.<br>
        - repeating gradients, which are fixed sized linear or radial gradients repeated as much as needed to fill the entire box.<br>
        <br>
        Definition from <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/gradient" rel="nofollow" target="_blank" id="ref">MDN - Mozilla Developer Network</a>
      </p>`
    },
    {
        title: "CSS Linear Gradients",
        content: `<strong>What is a CSS Linear Gradient?</strong>
        <br><br>
        <p class="quote">
          A linear gradient is created by specifying a straight gradient line, and then several colors placed along that line. The image is constructed by creating an infinite canvas and painting it with lines perpendicular to the gradient line, with the color of the painted line being the color of the gradient line where the two intersect. This produces a smooth fade from each color to the next, progressing in the specified direction.<br>
          <br>
          Definition from <a href="https://drafts.csswg.org/css-images-3/#linear-gradients" rel="nofollow" target="_blank" id="ref">W3C</a>
        </p>
        <br>
        Read more about how linear gradients works and how to generate them <a href="${URL}/linear-gradients" id="ref">here</a>.`
    },
    {
        title: "CSS Radial Gradients",
        content: `<strong>What is a CSS Radial Gradient?</strong>
        <br><br>
        <p class="quote">
          In a radial gradient, rather than colors smoothly fading from one side of the gradient box to the other as with linear gradients, they instead emerge from a single point and smoothly spread outward in a circular or elliptical shape.
          <br>
          A radial gradient is specified by indicating the center of the gradient (where the 0% ellipse will be) and the size and shape of the ending shape (the 100% ellipse). Color stops are given as a list, just as for linear-gradient(). Starting from the gradient center and progressing towards (and potentially beyond) the ending shape uniformly-scaled concentric ellipses are drawn and colored according to the specified color stops.<br>
          <br>
          Definition from <a href="https://drafts.csswg.org/css-images-3/#radial-gradients" rel="nofollow" target="_blank" id="ref">W3C</a>
        </p>
        <br>
        Read more about how radial gradients works and how to generate them <a href="${URL}/radial-gradients" id="ref">here</a>.`
    },
    {
        title: "CSS Text Gradients",
        content: `<strong>What is a CSS Text Gradient?</strong>
        <br><br>
        Using gradient on a text works the same way as the linear gradient, only that in this case you apply the gradient to a text instead of filling a background.<br>
        You'll love it. Just try to hover over the website logo on the left and you'll see for yourself.<br>
        <br>
        Read more about how linear gradients works and how to generate them <a href="${URL}/text-gradients" id="ref">here</a>.`
    },
    {
        title: "Where can I find more information about CSS gradients?",
        content: `      You can find more informaiton about CSS gradient at <a href="https://www.w3schools.com/csS/css3_gradients.asp" rel="nofollow" target="_blank" id="ref">W3Schools</a>, <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients" rel="nofollow" target="_blank" id="ref">Mozilla</a> <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient" rel="nofollow" target="_blank" id="ref">Developer</a> <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient" rel="nofollow" target="_blank" id="ref">Network</a>, <a href="https://www.w3.org/TR/css3-images/#gradients" rel="nofollow" target="_blank" id="ref">W3C</a>, <a href="http://www.quirksmode.org/css/images/gradients.html" rel="nofollow" target="_blank" id="ref">QuirksMode</a>.
        Compatibility Data from <a href="https://caniuse.com/#feat=css-gradients" rel="nofollow" target="_blank" id="ref">Can I Use</a>. More information about compatibility on <a href="http://www.quirksmode.org/css/images/gradients_desktop.html" rel="nofollow" target="_blank" id="ref">Desktop</a> and <a href="http://www.quirksmode.org/css/images/gradients_mobile.html" rel="nofollow" target="_blank" id="ref">Network</a>. `
    }
]
